version: '3.4'

services:
  frontend:
    image: frontend_med
    container_name: frontend_med
    build: .
    command: npm run start -- --disable-host-check --host 0.0.0.0
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - 4200:4200
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules

  fake_api:
    image: frontend_med
    container_name: frontend_med_api
    command: npm run db:start -- --host 0.0.0.0
    tty: true
    stdin_open: true
    profiles:
      - fake-api
    ports:
      - 3000:3000
    depends_on:
      - frontend
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
