version: '3.4'

services:
  frontend:
    container_name: frontend_med
    build: .
    command: npm run start -- --disable-host-check --host 0.0.0.0
    tty: true
    env_file:
      - .env
    ports:
      - 4200:4200
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules

